config/routes.rb
Rails.application.routes.draw do


  resources :lists
  resources :comments
  resources :email_subscribers
  resources :keywords
  resources :urls
  resources :users


  root 'sessions#new'

  get 'article_display'            => 'static_pages#article_display'
  post 'article_display'           => 'static_pages#article_display'
  get 'email_display'              => 'static_pages#email_display'
  post 'email_display'             => 'static_pages#article_display_email_list'
  get 'article_display_email_list' => 'static_pages#article_display_email_list'
  post 'sent_mail_review'          => 'static_pages#sent_mail_review'
  get 'sent_mail_review'           => 'static_pages#sent_mail_review'
  get 'list_view'                  => 'static_pages#list_view'
  post 'article_select_helper'     => 'static_pages#article_select_helper'
  post 'article_display_helper'    => 'static_pages#article_display_helper'
  get 'filtered_view'              => 'static_pages#filtered_view'
  post 'filtered_view'             => 'static_pages#filtered_view'
  get 'article_select'             => 'static_pages#article_select'
  post 'urls/new'                  => 'urls#new'

  get 'new'                        => 'user_url#new'
  post 'show'                      => 'user_url#new'

  get  '/login'                    => 'sessions#new'
  post '/login'                    => 'sessions#create'
  delete '/logout'                 => 'sessions#destroy'






end

app/models/list.rb
class List < ApplicationRecord
    validates_uniqueness_of :list_name
end

app/controllers/lists_controller.rb
class ListsController < ApplicationController
  before_action :set_list, only: [:show, :edit, :update, :destroy]

  # GET /lists
  # GET /lists.json
  def index
    @lists = List.all
    @email_subscribers = EmailSubscriber.all
    # @lists.each do |list|
    #   @idperlist = list.id
    #   @email_subscribers_perlist = EmailSubscriber.where(idperlist: email_subscribers.list_id)

  end

  # GET /lists/1
  # GET /lists/1.json
  def show
    @lists = List.all

    @email_subscribers = EmailSubscriber.all
  end

  # GET /lists/new
  def new
    @list = List.new
  end

  # GET /lists/1/edit
  def edit
    @list = List.find_by(params[:list_name])

    @email_subscribers = EmailSubscriber.all
  end

  # POST /lists
  # POST /lists.json
  def create
    @list = List.new(list_params)

    respond_to do |format|
      if @list.save
        format.html { redirect_to @list, notice: 'List was successfully created.' }
        format.json { render :show, status: :created, location: @list }
      else
        format.html { render :new }
        format.json { render json: @list.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /lists/1
  # PATCH/PUT /lists/1.json
  def update
    respond_to do |format|
      if @list.update(list_params)
        format.html { redirect_to @list, notice: 'List was successfully updated.' }
        format.json { render :show, status: :ok, location: @list }
      else
        format.html { render :edit }
        format.json { render json: @list.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /lists/1
  # DELETE /lists/1.json
  def destroy
    @list.destroy
    respond_to do |format|
      format.html { redirect_to lists_url, notice: 'List was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_list
      @list = List.find_by(params[:list_name])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def list_params
      params.require(:list).permit(:list_name)
    end
end

app/helpers/lists_helper.rb
module ListsHelper
end

app/views/lists/_form.html.erb
<%= form_for(list) do |f| %>
  <% if list.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(list.errors.count, "error") %> prohibited this list from being saved:</h2>

      <ul>
      <% list.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :list_name %>
    <%= f.text_field :list_name, :value => '' %>
  </div>

  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/lists/edit.html.erb
<h1>Editing List</h1>

<%= render 'form', list: @list %>


<p>Add User</p>
       <%= @list = params[:id] %>
       <br>
       <% if @email_subscribers %>
       <% @email_subscribers.each do |email_subscriber| %>

         <% if @list == email_subscriber.list_name %>
          <tr>
            <td><%= email_subscriber.name %></td>
            <td><%= email_subscriber.email %></td>
            <td><%= link_to 'Delete User', email_subscriber, method: :delete, data: { confirm: 'Are you sure?' } %></td>

          </tr>
          <br>
       <% end %>
       <% end %>
       <% end %>
    <%= link_to 'New Email Subscriber', controller: 'email_subscribers', action: "new", id: @list %>


<!-- add code for adding a user -->
<br>
<%= link_to 'Show', @list %>
<%= link_to 'Back', lists_path %>

app/views/lists/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Lists</h1>

<body>


    <% @lists.each do |list| %>

      <tr>
        <tr><%= list.list_name %></tr>


         <td><%= link_to 'Edit', controller: 'lists', action: "edit", id: list.list_name %></td>

         <td><%= link_to 'Delete', list, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>

      <br>
    <% end %>


</body>

<br>

<%= link_to 'New List', new_list_path %>
<%= link_to 'Home', home_path %>

app/views/lists/new.html.erb
<h1>New List</h1>

<%= render 'form', list: @list %>

<%= link_to 'Back', lists_path %>

app/views/lists/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>List name:</strong>
  <%= @list.list_name %>
  <% @lists.each do |list| %>


     <% @email_subscribers.each do |email_subscriber| %>
         <% if @list_name == email_subscriber.list_name %>
          <label><%= email_subscriber.name %></label>
          <label><%= email_subscriber.email %></label>
        <% end %>
     <% end %>
    <% end -%>
</p>
<%= link_to 'Edit', edit_list_path(@list) %> |
<%= link_to 'Back', lists_path %>