config/routes.rb
Rails.application.routes.draw do


  resources :lists
  resources :comments
  resources :email_subscribers
  resources :keywords
  resources :urls
  resources :users


  root 'sessions#new'

  get 'article_display'            => 'static_pages#article_display'
  post 'article_display'           => 'static_pages#article_display'
  get 'email_display'              => 'static_pages#email_display'
  post 'email_display'             => 'static_pages#article_display_email_list'
  get 'article_display_email_list' => 'static_pages#article_display_email_list'
  post 'sent_mail_review'          => 'static_pages#sent_mail_review'
  get 'sent_mail_review'           => 'static_pages#sent_mail_review'
  get 'list_view'                  => 'static_pages#list_view'
  post 'article_select_helper'     => 'static_pages#article_select_helper'
  post 'article_display_helper'    => 'static_pages#article_display_helper'
  get 'filtered_view'              => 'static_pages#filtered_view'
  post 'filtered_view'             => 'static_pages#filtered_view'
  get 'article_select'             => 'static_pages#article_select'
  post 'urls/new'                  => 'urls#new'

  get 'new'                        => 'user_url#new'
  post 'show'                      => 'user_url#new'

  get  '/login'                    => 'sessions#new'
  post '/login'                    => 'sessions#create'
  delete '/logout'                 => 'sessions#destroy'






end

app/controllers/static_pages_controller.rb
require 'rubygems'
require 'typhoeus'
require 'nokogiri'
require 'open-uri'
require 'net/http'
require 'mechanize'
require 'addressable/uri'
require 'delayed_job'
class StaticPagesController < ApplicationController
respond_to? :html

  def login_page
  end


  def home
    @title_arr = Array.new
    @user = User.find_by id: session[:user_id]


    @all_urls = Url.all
    @css_selectors_arr = Keyword.all

    @url_arr = Array.new
    @all_urls.each do |u|

    @page = Nokogiri::HTML(open(u.url))
    @url_arr.push(u.url)
    @title_arr.push(@page.css('title').text)



    end

  end



  def login
  end

  def graphs
  end

  def manage
   @title_arr = Array.new

    @all_urls = Url.all

    @url_arr = Array.new
    @all_urls.each do |u|



      @page = Nokogiri::HTML(open(u.url))
      @url_arr.push(u)
      @title_arr.push(@page.css('title').text)

  end


  end

  def payment

  end

  def profile
  end

  def search
  end

  def settings
  end


  def article_display
    if @parent = params["checked_arr"]
      @destringified_parent = Array.new
      @parent.each do |each|
        @destringified_parent.push(each)
      end
    end

    @checked_boxes = params[:list_name_ids]
    @all_comments = Comment.order(:created_at)


    @title_arr = Array.new
    @body_arr = Array.new
    @href_arr = Array.new

    @user = User.find_by id: session[:user_id]

    @all_urls = Url.all
    @test_url = Url.first
    @css_selectors_arr = Keyword.all
    @lists = List.all
    @test_var = 'test'

    respond_to do |format|
      format.js
    end

  end

  def article_display_email_list
    @email_subs_per_list = Array.new
    if @checked_arr = params["checked_arr"]
      @checked_arr.each do |list|
        EmailSubscriber.where(list_name: list).find_each do |subscriber|
          @email_subs_per_list.push(subscriber.email)
        end
      end
    end

      redirect_to email_display_path(:id => @email_subs_per_list)
  end

  def email_display
    @file = render_to_string :template => 'notifier_mailer/notify.html.erb'

  end



  def sent_mail_review
    if @send_to_arr = params["send_to_emails"]
      @send_to_arr.each do |sub|
        NotifierMailer.notify(sub).deliver
      end
      redirect_to sent_mail_review_path(:id => @send_to_arr)
    end

  end


  def list_view
    @urls = Url.all
  end


  def article_select_helper
    if @parent = params["checked_arr"]
      if @keyword = params["keyword"]
        redirect_to article_select_path(:parent => @parent, :keyword => @keyword)
      end
    end

    end

  def article_select
  end

  def filtered_view
    if @checked_urls = params["checked_arr"]
      if @keyword = params["keyword"]
        redirect_to filtered_view_path(:checked_urls => @checked_urls, :keyword => @keyword)
      end
    end
  end

end

app/helpers/static_pages_helper.rb
module StaticPagesHelper
end

app/views/static_pages/_notify.hmtl.erb
<p>This is a new website</p>

app/views/static_pages/article_display.html.erb
<!DOCTYPE html>
<html>
<head>
    <title>Article View</title>
</head>
<body>
<script src="https://ajax.googleapis.com/ajax/libs/jquery/1.12.4/jquery.min.js"></script>
<div id = "body-container">
    <div id = "mainDisplay">
        <div id = "headDisplay">
            <%= @test.inspect %>
        </div>
        <div id = "articleBody">


        </div>
        <div id = "articleImages">

        </div>
   </div>
    <div id = "sideTools">
        <div id = "emailList">
            <div id="col-header">
                <h3>Email List</h3>


            </div>
            <ul id = "email_lists">
            <% @lists.each do |list| %>
                <li><label><input id=<%= list.list_name %> type="checkbox" value=<%= list.list_name %> ><%= list.list_name %></label></li>
            <% end -%>
            </ul>


            <input id="list_checkboxes" type="button" value="Email Blast"/>
            <label id = 'checked_arr'></label>


        </div>
        <div id = "comments">
            <div id="col-header">
            <h3>Comments</h3>

            </div>

            <div id="comments_section">
                <ul id="comments_list">
                    <% @all_comments.each do |c| %>
                        <li><span id="commentUsername"><%= c.username %></span><br> <%= c.comment %><br> <%= c.created_at %> </li>
                    <% end %>


                </ul>
            </div>
            <div id = "comment_submit">

                <%= form_for Comment.new do |f| %>

                  <div hidden class="field">
                    <%= f.label :username %>
                    <%= f.text_field :username, required: true, value: @user.username %>
                  </div>

                  <div class="comment_in_form">
                  <br>
                    <%= f.label :comment %>
                    <%= f.text_field :comment %>
                  </div>

                  <div hidden class="field">
                    <%= f.label :url %>
                    <%= f.text_field :url, required: true, value: @test_url.url %>
                  </div>

                  <div class="actions">
                    <%= f.button :submit, name: "comment_text", value: "comment" %>
                  </div>
                <% end %>

            </div>
        </div>
    </div>
</div>
<script type="text/javascript">
    var list_arr = <%= raw @lists.to_json %>;
    var list_name_arr = [];
    for(var i = 0; i < list_arr.length; i++) {
        list_name_arr.push(list_arr[i]["list_name"]);
    };
    var checked_arr = [];

        $(document).ready(function() {
        $("body").on("click", "#list_checkboxes", function () {
            for (var i = 0; i < list_name_arr.length; i++) {
                if(document.getElementById(list_name_arr[i]).checked) {
                    checked_arr.push(list_name_arr[i]);
                };
            };

            alert('before ajax');
            $.ajax({
                url: '/email_display',
                type: 'POST',
                beforeSend: function(xhr) {xhr.setRequestHeader('X-CSRF-Token', $('meta[name="csrf-token"]').attr('content'))},
                data: { checked_arr },

                success: function() {
                    alert('success');
                }
            });


        });
    });

</script>
</body>

</html>

app/views/static_pages/article_display.js.erb
$('body').fadeOut(2000);
var parent = <%= raw @parent %>;
alert(parent);

app/views/static_pages/article_display_email_list.html.erb
<!DOCTYPE html>
<html>
<head>
    <title></title>
</head>
<h1>Successful</h1>
<body>
<% @checked_arr_permanant %>

</body>
<script>
alert("yo");
alert(@checked_arr_permanant);
</script>
</html>

app/views/static_pages/article_select.html.erb
<!DOCTYPE html>
<html>
<head>
    <title>Article Select</title>
</head>
<body>

<% if @parent = params[:parent] %> <!-- #all of the checkmarked parent websites -->
    <%  @titles = Array.new  %>
    <%  @filted_articles = Array.new %>
    <%  @all_child_data = Array.new %>

    <%  @articles_return = Array.new %> <!-- #array for all of the filtered urls to be added to -->
    <%  if @keyword = params[:keyword] %>
    <%    @r1 = Regexp.new(@keyword.downcase) %> <!-- #create regular exp -->
    <%  end %>
    <%   @parent.each do |e| %>
    <%    @response = Typhoeus.get(e, ssl_verifyhost: 0) %>
    <%    @body = Nokogiri::HTML(@response.body) %>
    <%    @select_text = @body.xpath("//a/@href")  %>  <!-- #Grabs all href's within a tags within url -->
    <%    @select_text.each do |href| %>
    <%    href = href.to_s %>
    <%    if (/http/ =~ href) != nil  %>   <!-- # If it contains http -->
    <%    if (/.jpg/ =~ href) == nil && (/.png/ =~ href) == nil %><!--  # If it doesn't contain .jpg or .png -->
    <%     @response = Typhoeus.get(href, ssl_verifyhost: 0) %><!--  # makes a request to the href http tag within url -->
    <%     @child_body = Nokogiri::HTML(@response.body) %> <!--  # gets the html of the url -->
    <%      @all_p_tags = @child_body.xpath("//body//p").inner_html %>
    <%      @all_p_tags.force_encoding(Encoding::UTF_8) %>
    <%      if !@all_p_tags.valid_encoding? %>
                  <%  for i in (0...@all_p_tags.size) %>
                   <%   if !@all_p_tags[i].valid_encoding? %>
                    <%  @all_p_tags[i]="?" %>
                    <% end %>
                   <% end %>
                  <% end %>

                 <% if (@r1 =~ @all_p_tags) != nil %>
                 <!-- create hash for child  -->
    <%                @title = @child_body.xpath("//title").inner_html %>
    <%                @child_url = href %>
    <%                @date_response = Faraday.head(href) %>
    <%                @temp = @date_response['Last-Modified'] %>
    <%                if @temp.present? %>
    <%                  @child_date = @temp %>
    <%                end %>
    <%                @hash = {:title => @title, :body => @all_p_tags, :url => @child_url, :date => @child_date.to_s} %>
    <%                @all_child_data.push(@hash) %>
    <%            end %>
    <%          end %>
    <%        end %>
    <%      end %>
    <%    end %>
    <%  end %>
<div id = "article_list">
<tr>
    <% @all_child_data.each do |match| %>
    <label>
    <tr>
       <h2> <%= match[:title] %> </h2>
        <%= match[:body] %><br>
        <%= match[:url] %> <br>
        <%= match[:date] %>
        <%= check_box_tag 'all_child_data', match %> Select this article for further viewing?
    </tr>
    </label>
    <% end %>

</tr>
<br>
<br>
<br>
<br>
<button id="to_listicle_view"> Review Selected Articles </button> <br>

<%= link_to 'Back', url_for(:back) %>
</div>
<script type="text/javascript">
    // var url_name_arr = [];
    // for(var i = 0; i < all_child_data.length; i++) {
    //     url_name_arr.push(all_child_data[i][:]);
    // };
    var checked_arr = [];
        $(document).ready(function() {
        $("body").on("click", "#to_listicle_view", function() {
            $('input:checkbox[id=all_child_data]:checked').each(function() {
                checked_arr.push(this.value);
            })
            $.ajax({
                url: 'article_display',
                type: 'POST',
                format: 'html',
                beforeSend: function(xhr) {xhr.setRequestHeader('X-CSRF-Token', $('meta[name="csrf-token"]').attr('content'))},
                data: { checked_arr },
                success: function() {
                }
            })
    });
});

</script>
</body>
</html>

app/views/static_pages/email_display.html.erb
<!DOCTYPE html>
<html>
<head>
    <title></title>
</head>
<h1>Successful Redirect</h1>
<body>


 <div hidden>
<% @temp = params[:id] %>
 </div>
<% @email_subs_per_list = @temp %>
<br>
<br>
<h3>Edit the following template email to send to your subscribers. </h3>
<div id = "includeDisplay"></div>
<br>
<br>
<br>
<h3>Send Email to the following addresses?</h3>
<% @email_subs_per_list.each do |sub| %>
    <%= sub.inspect %>
    <br>
<% end %>
<br>


<input type="button" id="send_via_ajax" value="Send Mail!"/>
<%= link_to 'Article Display', article_display_path %>


<script type="text/javascript">
    var send_to_emails = <%= raw @email_subs_per_list %>;
    $(document).ready(function() {
        $("body").on("click", "#send_via_ajax", function() {
            $.ajax({
                url: 'sent_mail_review',
                type: 'POST',
                beforeSend: function(xhr) {xhr.setRequestHeader('X-CSRF-Token', $('meta[name="csrf-token"]').attr('content'))},
                data: { send_to_emails },
                success: function() {
                    alert("sent!");
                }

            })
        })
    })


</script>
</body>

</html>

app/views/static_pages/filtered_view.html.erb
<!DOCTYPE html>
<html>
<head>
    <title>Filtered View</title>
</head>
<body>
<h2>Articles that matched your search results:</h2>
<% @regex = params[:keyword].downcase %>
<% @r1 = Regexp.new(@regex) %>
<% @checked_urls = params[:checked_urls] %>
<div id="checked_list">
 <% @checked_urls.each do |u| %>
    <% u %>
    <br>
 <% end %>
<h2>Select which articles to view:</h2>



<% @articles_return = Array.new %>
<% @checked_urls.each do |e| %>
    <% @response = Typhoeus.get(e, ssl_verifyhost: 0) %>
    <% @body = Nokogiri::HTML(@response.body) %>
    <% @select_text = @body.xpath("//a/@href") %>  <!--Grabs all href's within a tags within url-->
    <% @select_text.each do |href| %>
<% @titles = Array.new %>
        <% if (/http/ =~ href) != nil %>   <!-- If it contains http -->
                <% if (/.jpg/ =~ href) == nil && (/.png/ =~ href) == nil %> <!-- If it doesn't contain .jpg or .png -->
                    <% if (@r1 =~ href) %>

                        <% @articles_return.push(href.to_s) %>

                    <% else %>

                        <% @response_inner = Typhoeus.get(href, ssl_verifyhost: 0) %> <!-- makes a request to the href http tag within url -->
                        <% @body_inner = Nokogiri::HTML(@response_inner.body) %> <!-- gets the body of the url -->
                        <% @body_scannable = @body_inner.xpath("//body/p").to_s %>


                        <% if (@r1 =~ @body_scannable) != nil %> <!--if the body contains the keyword -->
                        <% @articles_return.push(href.to_s) %>
                        <% end %>



                    <% end %>
            <% end %>
        <% end %>
    <% end %>
<% end %>
<% @articles_uniq = @articles_return.uniq %>

<% @articles_uniq.each do |article| %>
    <% @response_articles = Typhoeus.get(article, ssl_verifyhost: 0) %>
    <% @body_article = Nokogiri::HTML(@response_articles.body) %>
    <% if (@titles.include? @body_article.xpath("//title").inner_text) == false %>
    <% @flag = true %>
        <% @titles.push(@body_article.xpath("//title").inner_text) %>
    <% else %>
        <% @flag = false %>
    <% end %>
    <% if @flag %>
        <% @response = Faraday.head(article) %>
        <% @last = @response['Last-Modified'] %>
        <% if @last.present? %>
        <label><input id=<%= article %> type="checkbox" value=<%= article %> ><%= @titles.last %> <%= @last.inspect %></label>
        <% end %>
    <% end %>
<% end %>


<button id="send_to_article_display">Display Articles</button>
<%= link_to 'Back', list_view_path %>

 </div>
 <script type="text/javascript">
    var articles_list_arr = <%= raw @articles_uniq.to_json %>;
    alert("articles in uniq array: " + articles_list_arr);
    var articles_name_arr = [];
    for(var i = 0; i < articles_list_arr.length; i++) {
        articles_name_arr.push(articles_list_arr[i]);
    };
    var article_arr = [];
    alert("article names: " + articles_name_arr.length);

        $(document).ready(function() {
        $("body").on("click", "#send_to_article_display", function () {
            alert('hello');
            for (var i = 0; i < articles_name_arr.length; i++) {
                if(document.getElementById(articles_name_arr[i]).checked) {
                    alert("added" + articles_name_arr[i]);
                    article_arr.push(articles_name_arr[i]);
                };
                alert(i);
            };

            alert('before ajax');
            $.ajax({
                url: '/article_display',
                type: 'POST',
                beforeSend: function(xhr) {xhr.setRequestHeader('X-CSRF-Token', $('meta[name="csrf-token"]').attr('content'))},
                data: { article_arr },

                success: function() {
                    alert('success');
                }
            })
    });
});

</script>
</body>
</html>

app/views/static_pages/list_view.html.erb
<!DOCTYPE html>
<html>
<head>
    <title></title>
</head>
<body>
<h3>Articles:</h3>
    <div id="search_list_view">
    <input id='search_text' type="search_text" name="Search Articles">
    <button id="to_article_view">View/Edit Articles</button>
    <%= button_to "Add Websites", new_url_path  %>


</div>
<div id="search_container">
    <div id="search_side_bar_list_view">

    </div>
    <div id="articles_list_view">
    <% @urls.each do |u| %>
    <label><input id=<%= u.url %> type="checkbox" value=<%= u.url %> ><%= u.url %></label>
    <%end%>
    </div>
    <div id="articles_filtered_list_view">


   <ul id= "child_list">

   </ul>


    </div>
</div>
<script type="text/javascript">
    var url_list_arr = <%= raw @urls.to_json %>;
    var url_name_arr = [];
    for(var i = 0; i < url_list_arr.length; i++) {
        url_name_arr.push(url_list_arr[i]["url"]);
    };
    var checked_arr = [];

        $(document).ready(function() {
        $("body").on("click", "#to_article_view", function () {

            var keyword = document.getElementById("search_text").value;
            for (var i = 0; i < url_name_arr.length; i++) {
                if(document.getElementById(url_name_arr[i]).checked) {
                    alert("added" + url_name_arr[i]);
                    checked_arr.push(url_name_arr[i]);
                };
            };
            $.ajax({
                url: 'article_select_helper',
                type: 'POST',
                beforeSend: function(xhr) {xhr.setRequestHeader('X-CSRF-Token', $('meta[name="csrf-token"]').attr('content'))},
                data: { checked_arr, keyword },
                success: function() {
                    alert('success');

                }
            })
    });
});

</script>
</body>
</html>

app/views/static_pages/list_view.js.erb
if <% @parent = params["checked_arr"] %> //all of the checkmarked parent websites
    @titles = Array.new
    @filted_articles = Array.new
    @articles_return = Array.new //array for all of the filtered urls to be added to
    @all_child_data = Array.new //array  that contains a hash of data for each child
        if @keyword = params["keyword"]
          @r1 = Regexp.new(@keyword.downcase) //create regular exp
        end
        @parent.each do |e|
          @response = Typhoeus.get(e, ssl_verifyhost: 0)
          @body = Nokogiri::HTML(@response.body)
          @select_text = @body.xpath("//a/@href")   //Grabs all href's within a tags within url
          @select_text.each do |href|
             if (/http/ =~ href) != nil    // If it contains http
                  if (/.jpg/ =~ href) == nil && (/.png/ =~ href) == nil  // If it doesn't contain .jpg or .png
                    @response = Typhoeus.get(href, ssl_verifyhost: 0)  // makes a request to the href http tag within url
                    @child_body = Nokogiri::HTML(@response.body)  // gets the body of the url
                    @all_p_tags = @child_body.xpath("//body/p").to_s
                    if (@r1 =~ @all_p_tags) != nil
                        //create hash for child
                        @title = @child_body.xpath("//title").to_s
                        @child_url = href
                        @date_response = Faraday.head(href)
                        @temp = @date_response['Last-Modified']
                        if @temp.present?
                          @child_date = @temp
                        end
                        @hash = {:title => @title, :body => @all_p_tags, :url => @child_url, :date => @child_date.to_s}
                        @all_child_data.push(@hash)
                    end
                  end
             end
          end
        end
    end

app/views/static_pages/login_page.html.erb
<!DOCTYPE html>
<html>
<head>
    <title>Login Page</title>

</head>
<body>

<h3>Continue to Home Page</h3>


<%= link_to "Home Page", home_path %>


<br></br>

<% form_for(:session, url: login_path) do |f| %>

    <%= f.label :email  %>
    <%= f.email_field :email, class: "form-control" %>

    <%= f.label :password %>
    <%= f.password_field :password, class: "form-control" %>

    <%= f.submit "Login", class: "btn-primary" %>
<% end -%>

<br></br>


<div hidden id = "home_page_button"><%= link_to "Home Page", home_path %>
</div>
</script>
</body>
</html>

app/views/static_pages/sent_mail_review.html.erb
<!DOCTYPE html>
<html>
<head>
    <title></title>
</head>
<body>
<div hidden>
<%= @temp = params[:id] %>
<%= @sent_to = @temp %>
</div>
<h3>Sent Mail:</h3>
<% @sent_to.each do |sent| %>
    <%= sent.inspect %>
<% end %>
<h4>Opened:</h4>
<h4>Unopened:</h4>

</body>
</html>