config/routes.rb
Rails.application.routes.draw do


  resources :lists
  resources :comments
  resources :email_subscribers
  resources :keywords
  resources :urls
  resources :users


  root 'sessions#new'

  get 'article_display'            => 'static_pages#article_display'
  post 'article_display'           => 'static_pages#article_display'
  get 'email_display'              => 'static_pages#email_display'
  post 'email_display'             => 'static_pages#article_display_email_list'
  get 'article_display_email_list' => 'static_pages#article_display_email_list'
  post 'sent_mail_review'          => 'static_pages#sent_mail_review'
  get 'sent_mail_review'           => 'static_pages#sent_mail_review'
  get 'list_view'                  => 'static_pages#list_view'
  post 'article_select_helper'     => 'static_pages#article_select_helper'
  post 'article_display_helper'    => 'static_pages#article_display_helper'
  get 'filtered_view'              => 'static_pages#filtered_view'
  post 'filtered_view'             => 'static_pages#filtered_view'
  get 'article_select'             => 'static_pages#article_select'
  post 'urls/new'                  => 'urls#new'

  get 'new'                        => 'user_url#new'
  post 'show'                      => 'user_url#new'

  get  '/login'                    => 'sessions#new'
  post '/login'                    => 'sessions#create'
  delete '/logout'                 => 'sessions#destroy'






end

app/models/application_record.rb
 class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/comment.rb
class Comment < ApplicationRecord
end

app/models/email_subscriber.rb
class EmailSubscriber < ApplicationRecord
end

app/models/keyword.rb
class Keyword < ApplicationRecord
end

app/models/list.rb
class List < ApplicationRecord
    validates_uniqueness_of :list_name
end

app/models/url.rb
class Url < ApplicationRecord
    validates :url, uniqueness: true




end

app/models/user.rb
class User < ApplicationRecord




  attr_accessor :remember_token
  before_save { self.email = self.email.downcase }
  validates :username, presence: true, length: { maximum: 50 }
  VALID_EMAIL = /\A[\w+\-.]+@[a-z\d\-.]+\.[a-z]+\z/i
  validates :email, presence: true, length: { maximum: 255 },
                    format: { with: VALID_EMAIL },
                    uniqueness: { case_sensitive: false }
  has_secure_password
  validates :password, presence: true, length: { minimum: 6 }


  def User.new_token
    SecureRandom.urlsafe_base64

  end


  def User.digest(string)
    cost = ActiveModel::SecurePassword.min_cost ? BCrypt::Engine::MIN_COST :
                                                  BCrypt::Engine.cost
    BCrypt::Password.create(string, cost: cost)
  end

  def remember
    self.remember_token = User.new_token
    update_attribute(:remember_digest, User.digest(remember_token))

  end

  def authenticated?(remember_token)
    BCrypt::Password.new(remember_digest).is_password?(remember_token)
  end

  def forget
    update_attribute(:remember_digest, nil)
  end

end

app/controllers/email_subscribers_controller.rb
class EmailSubscribersController < ApplicationController
  before_action :set_email_subscriber, only: [:show, :edit, :update, :destroy]

  # GET /email_subscribers
  # GET /email_subscribers.json
  def index
    @email_subscribers = EmailSubscriber.all
  end

  # GET /email_subscribers/1
  # GET /email_subscribers/1.json
  def show
  end

  # GET /email_subscribers/new
  def new
    @email_subscriber = EmailSubscriber.new
    @list = List.find_by(params[:list_name])

  end

  # GET /email_subscribers/1/edit
  def edit
  end

  # POST /email_subscribers
  # POST /email_subscribers.json
  def create
    @email_subscriber = EmailSubscriber.new(email_subscriber_params)

    respond_to do |format|
      if @email_subscriber.save
        format.html { redirect_to @email_subscriber, notice: 'Email subscriber was successfully created.' }
        format.json { render :show, status: :created, location: @email_subscriber }
      else
        format.html { render :new }
        format.json { render json: @email_subscriber.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /email_subscribers/1
  # PATCH/PUT /email_subscribers/1.json
  def update
    respond_to do |format|
      if @email_subscriber.update(email_subscriber_params)
        format.html { redirect_to @email_subscriber, notice: 'Email subscriber was successfully updated.' }
        format.json { render :show, status: :ok, location: @email_subscriber }
      else
        format.html { render :edit }
        format.json { render json: @email_subscriber.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /email_subscribers/1
  # DELETE /email_subscribers/1.json
  def destroy
    @email_subscriber.destroy
    respond_to do |format|
      format.html { redirect_to email_subscribers_url, notice: 'Email subscriber was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_email_subscriber
      @email_subscriber = EmailSubscriber.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def email_subscriber_params
      params.require(:email_subscriber).permit(:name, :email, :list_name)
    end
end

app/controllers/urls_controller.rb
class UrlsController < ApplicationController
  before_action :set_url, only: [:show, :edit, :update, :destroy]

  # GET /urls
  # GET /urls.json
  def index
    @user_id = session[:user_id]
    @urls = Url.all
  end

  # GET /urls/1
  # GET /urls/1.json
  def show
  end

  # GET /urls/new
  def new
    @url = Url.new
  end

  # GET /urls/1/edit
  def edit
  end

  # POST /urls
  # POST /urls.json
  def create
    @url = Url.new(url_params)

    respond_to do |format|
      if @url.save
        format.html { redirect_to @url, notice: 'Url was successfully created.' }
        format.json { render :show, status: :created, location: @url }
      else
        format.html { render :new }
        format.json { render json: @url.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /urls/1
  # PATCH/PUT /urls/1.json
  def update
    respond_to do |format|
      if @url.update(url_params)
        format.html { redirect_to @url, notice: 'Url was successfully updated.' }
        format.json { render :show, status: :ok, location: @url }
      else
        format.html { render :edit }
        format.json { render json: @url.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /urls/1
  # DELETE /urls/1.json
  def destroy
    @url.destroy
    respond_to do |format|
      format.html { redirect_to urls_url, notice: 'Url was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_url
      @url = Url.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def url_params
      params.require(:url).permit(:url)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/auth0_helper.rb
module Auth0Helper
end

app/helpers/comments_helper.rb
module CommentsHelper
end

app/helpers/email_subscribers_helper.rb
module EmailSubscribersHelper
end

app/helpers/keywords_helper.rb
module KeywordsHelper
end

app/helpers/lists_helper.rb
module ListsHelper
end

app/helpers/scrapes_helper.rb
module ScrapesHelper
end

app/helpers/secure_helper.rb
module SecureHelper
end

app/helpers/secured_helper.rb
module SecuredHelper
end

app/helpers/sessions_helper.rb
module SessionsHelper

    def login(user)
        session[:user_id] = user.id
    end

    def current_user
        if (user_id = session[:user_id])
              @current_user ||= User.find_by(id: user_id)
            elsif (user_id = cookies.signed[:user_id])
              user = User.find_by(id: user_id)
              if user && user.authenticated?(cookies[:remember_token])
                log_in user
                @current_user = user
              end
        end
    end

    def logged_in
        !current_user.nil?
    end

    def logout
        session.delete(:user_id)
        @current_user = nil
    end

    def remember(user)
        user.remember
        cookies.permanent.signed[:user_id] = user.id
        cookies.permanent[:remember_token] = user.remember_token
    end

    def forget(current_user)
        session.delete(:user_id)
        @current_user = nil

    end

end

app/helpers/static_pages_helper.rb
module StaticPagesHelper
end

app/helpers/urls_helper.rb
module UrlsHelper
end

app/helpers/user_url_helper.rb
module UserUrlHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/email_subscribers/_form.html.erb
<%= form_for(email_subscriber) do |f| %>
  <% if email_subscriber.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(email_subscriber.errors.count, "error") %> prohibited this email_subscriber from being saved:</h2>

      <ul>
      <% email_subscriber.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :name %>
    <%= f.text_field :name %>
  </div>

  <div class="field">
    <%= f.label :email %>
    <%= f.text_field :email %>
  </div>

  <div hidden class="field">
    <%= f.label :list_name %>
    <%= f.text_field :list_name, :value => params[:id] %>
  </div>

  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/email_subscribers/edit.html.erb
<h1>Editing Email Subscriber</h1>

<%= render 'form', email_subscriber: @email_subscriber %>

<%= link_to 'Show', @email_subscriber %> |
<%= link_to 'Back', email_subscribers_path %>

app/views/email_subscribers/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Email Subscribers</h1>

<table>
  <thead>
    <tr>
      <th>Name</th>
      <th>Email</th>
      <th>List name</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @email_subscribers.each do |email_subscriber| %>
      <tr>
        <td><%= email_subscriber.name %></td>
        <td><%= email_subscriber.email %></td>
        <td><%= email_subscriber.list_name %></td>
        <td><%= link_to 'Show', email_subscriber %></td>
        <td><%= link_to 'Edit', edit_email_subscriber_path(email_subscriber) %></td>
        <td><%= link_to 'Destroy', email_subscriber, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Email Subscriber', new_email_subscriber_path %>
<%= link_to 'Lists', new_list_path %>

app/views/email_subscribers/new.html.erb
<h1>New Email Subscriber</h1>

<%= render 'form', email_subscriber: @email_subscriber %>


<%= link_to 'Back', controller: 'lists', action: "edit", id: @list.list_name %>

app/views/email_subscribers/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Name:</strong>
  <%= @email_subscriber.name %>
</p>

<p>
  <strong>Email:</strong>
  <%= @email_subscriber.email %>
</p>

<p>
  <strong>List name:</strong>
  <%= @email_subscriber.list_name %>
</p>

<%= link_to 'Edit', edit_email_subscriber_path(@email_subscriber) %> |
<%= link_to 'Back', lists_path %>