config/routes.rb
Rails.application.routes.draw do


  resources :lists
  resources :comments
  resources :email_subscribers
  resources :keywords
  resources :urls
  resources :users


  root 'sessions#new'

  get 'article_display'            => 'static_pages#article_display'
  post 'article_display'           => 'static_pages#article_display'
  get 'email_display'              => 'static_pages#email_display'
  post 'email_display'             => 'static_pages#article_display_email_list'
  get 'article_display_email_list' => 'static_pages#article_display_email_list'
  post 'sent_mail_review'          => 'static_pages#sent_mail_review'
  get 'sent_mail_review'           => 'static_pages#sent_mail_review'
  get 'list_view'                  => 'static_pages#list_view'
  post 'article_select_helper'     => 'static_pages#article_select_helper'
  post 'article_display_helper'    => 'static_pages#article_display_helper'
  get 'filtered_view'              => 'static_pages#filtered_view'
  post 'filtered_view'             => 'static_pages#filtered_view'
  get 'article_select'             => 'static_pages#article_select'
  post 'urls/new'                  => 'urls#new'

  get 'new'                        => 'user_url#new'
  post 'show'                      => 'user_url#new'

  get  '/login'                    => 'sessions#new'
  post '/login'                    => 'sessions#create'
  delete '/logout'                 => 'sessions#destroy'






end

app/models/url.rb
class Url < ApplicationRecord
    validates :url, uniqueness: true




end

app/controllers/urls_controller.rb
class UrlsController < ApplicationController
  before_action :set_url, only: [:show, :edit, :update, :destroy]

  # GET /urls
  # GET /urls.json
  def index
    @user_id = session[:user_id]
    @urls = Url.all
  end

  # GET /urls/1
  # GET /urls/1.json
  def show
  end

  # GET /urls/new
  def new
    @url = Url.new
  end

  # GET /urls/1/edit
  def edit
  end

  # POST /urls
  # POST /urls.json
  def create
    @url = Url.new(url_params)

    respond_to do |format|
      if @url.save
        format.html { redirect_to @url, notice: 'Url was successfully created.' }
        format.json { render :show, status: :created, location: @url }
      else
        format.html { render :new }
        format.json { render json: @url.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /urls/1
  # PATCH/PUT /urls/1.json
  def update
    respond_to do |format|
      if @url.update(url_params)
        format.html { redirect_to @url, notice: 'Url was successfully updated.' }
        format.json { render :show, status: :ok, location: @url }
      else
        format.html { render :edit }
        format.json { render json: @url.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /urls/1
  # DELETE /urls/1.json
  def destroy
    @url.destroy
    respond_to do |format|
      format.html { redirect_to urls_url, notice: 'Url was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_url
      @url = Url.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def url_params
      params.require(:url).permit(:url)
    end
end

app/helpers/urls_helper.rb
module UrlsHelper
end

app/views/urls/_form.html.erb
<%= form_for(url) do |f| %>
  <% if url.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(url.errors.count, "error") %> prohibited this url from being saved:</h2>

      <ul>
      <% url.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :url %>
    <%= f.text_field :url %>
  </div>

  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/urls/edit.html.erb
<h1>Editing Url</h1>

<%= render 'form', url: @url %>

<%= link_to 'Show', @url %> |
<%= link_to 'Back', urls_path %>

app/views/urls/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Urls</h1>

<table>
  <thead>
    <tr>
      <th>Url</th>
      <th colspan="3"></th>
    </tr>
  </thead>
  <p> User ID: <%= session[:user_id].inspect %></p>

  <tbody>
    <% @urls.each do |url| %>
      <tr>
        <td><%= url.url %></td>
        <td><%= link_to 'Show', url %></td>
        <td><%= link_to 'Edit', edit_url_path(url) %></td>
        <td><%= link_to 'Destroy', url, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Url', new_url_path %>
<%= link_to 'Back', url_for(:back) %>

app/views/urls/new.html.erb
<h1>New Url</h1>

<%= render 'form', url: @url %>

<%= link_to 'Back', urls_path %>
<%= link_to 'Show', show_path %>

app/views/urls/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Url:</strong>
  <%= @url.url %>
</p>

<%= link_to 'Edit', edit_url_path(@url) %> |
<%= link_to 'Back', urls_path %>